const userConstants = {
    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_REQUEST_SUCCESS: 'GET_ALL_USERS_REQUEST_SUCCESS',
    GET_ALL_USERS_REQUEST_FAILURE: 'GET_ALL_USERS_REQUEST_FAILURE',
}

export default userConstants;